// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuyrmtbdleznvpjphxir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1eXJtdGJkbGV6bnZwanBoeGlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjM3ODgsImV4cCI6MjA2MDI5OTc4OH0.oHWo0_pJbpE-OybZgLTUjiUfEiiDPj_w4VXYQf4okaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);